version: "3.8"
services:
  # PHP Service
  php:
    container_name: php
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis
    networks:
      - laravel-chat-app

    # Database Server
  database:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-chat-app

  # Redis Server
  redis:
    container_name: redis
    image: redis:alpine
#    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - laravel-chat-app

  # Node Server
  node:
    container_name: node
    build:
      context: .
      target: node
    volumes:
      - .:/usr/source
      - ./node_modules:/usr/source/node_modules
    tty: true
networks:
  laravel-chat-app:
    name: laravel-chat-app
volumes:
  db-data: ~


